apiVersion: v1
kind: List
metadata:
  resourceVersion: ""
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    generation: 1
    labels:
      app: pod1
    name: pod1
    namespace: restricted
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: pod1
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: pod1
      spec:
        automountServiceAccountToken: false
        containers:
        - image: nginx:1.19.2-alpine
          imagePullPolicy: IfNotPresent
          name: c
          resources:
            requests:
              cpu: 20m
              memory: 20Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/secret-volume
            name: secret-volume
            readOnly: true
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: secret-access
        serviceAccountName: secret-access
        terminationGracePeriodSeconds: 30
        volumes:
        - name: secret-volume
          secret:
            defaultMode: 420
            secretName: secret1
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    generation: 1
    labels:
      app: pod2
    name: pod2
    namespace: restricted
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: pod2
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: pod2
      spec:
        automountServiceAccountToken: false
        containers:
        - env:
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: secret2
          image: nginx:1.19.2-alpine
          imagePullPolicy: IfNotPresent
          name: c
          resources:
            requests:
              cpu: 20m
              memory: 20Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: secret-access
        serviceAccountName: secret-access
        terminationGracePeriodSeconds: 30
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    generation: 1
    labels:
      app: pod3
    name: pod3
    namespace: restricted
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: pod3
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: pod3
      spec:
        containers:
        - image: nginx:1.19.2-alpine
          imagePullPolicy: IfNotPresent
          name: c
          resources:
            requests:
              cpu: 20m
              memory: 20Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: secret-access
        serviceAccountName: secret-access
        terminationGracePeriodSeconds: 30
