apiVersion: v1
kind: List
metadata:
  resourceVersion: ""
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: restricted
    namespace: restricted
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: restricted
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: restricted
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: secret-access
    namespace: restricted
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: secret-access
  subjects:
  - kind: ServiceAccount
    name: secret-access
    namespace: restricted

