apiVersion: v1
kind: List
metadata:
  resourceVersion: ""
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: restricted
    namespace: restricted
  rules:
  - apiGroups:
    - '*'
    resources:
    - pods
    verbs:
    - list
    - get
  - apiGroups:
    - ""
    resources:
    - pods/exec
    verbs:
    - create
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: secret-access
    namespace: restricted
  rules:
  - apiGroups:
    - ""
    - extensions
    - apps
    resources:
    - secrets
    verbs:
    - '*'

