apiVersion: v1
kind: List
metadata:
  resourceVersion: ""
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: default
    namespace: restricted

- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: secret-access
    namespace: restricted

